### ISSUE TITLE
Cannot find "%AppData%\Local\OpenXbox\Xbox"

### ISSUE THREAD

**Issue by Arlodotexe** [OpenXbox/xbox-smartglass-core-python#1]
I am running Windows 10 version 1803, running Python 3.6.5. While trying to use any of the tools from the SmartGlass Core, I get the following error: 

```PS C:\> xbox-authenticate
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\Scripts\xbox-authenticate.exe\__main__.py", line 5, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xbox\webapi\scripts\__init__.py", line 8, in <module>
    os.mkdir(DATA_DIR)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\User\\AppData\\Local\\OpenXbox\\xbox'
```
I've made sure that the Python folder as well as the Scripts folder are present on my PATH, and I'm not sure where to go from here.

**Comment by tuxuser** [comment]
Please create following directory, then retry:

```
C:\\Users\\User\\AppData\\Local\\OpenXbox\\xbox
```

UPDATE: Just update `xbox-smartglass-core` via pip, issue is fixed!
