### ISSUE TITLE
Media seek endpoint: TypeError: send_media_command() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-core-python#22]
Tried the seek command via

```
curl -X GET -i 'http://192.168.178.65:5557/device/myliveid/media/seek/5
```

but rest server gets error 500 with following log:

```
[2018-11-19 16:19:50,188] ERROR in app: Exception on /device/myliveid/media/seek/5 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.5/site-packages/xbox/rest/decorators.py", line 21, in decorated_function
    return f(*args, **kwargs)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.5/site-packages/xbox/rest/routes/device.py", line 214, in media_command_seek
    console.send_media_command(enum.MediaControlCommand.Seek, seek_position)
TypeError: send_media_command() takes 2 positional arguments but 3 were given
192.168.178.37 - - [2018-11-19 16:19:50] "GET /device/myliveid/media/seek/5 HTTP/1.1" 500 412 0.021084
```

**Comment by tuxuser** [comment]
It took over a year - but its finally fixed in upstream.

**Comment by foxriver76** [comment]
Lol ;-) thanks
