### ISSUE TITLE
Cannot authenticate on rest server with v1.2.1

### ISSUE THREAD

**Issue by foxriver76** [OpenXbox/xbox-smartglass-core-python#30]
Getting the following error response `"message":"Unhandled authentication error: expected str, bytes or os.PathLike object, not NoneType"`

On client side nothing has changed, also the errors does not really make sense as response.

```
127.0.0.1 - - [2020-04-01 23:35:36] "GET /auth HTTP/1.1" 200 1915 0.007661
[2020-04-01 23:35:38,664] ERROR: {'success': False, 'message': 'Unhandled authentication error: expected str, bytes or os.PathLike object, not NoneType', 'two_factor_required': False}
127.0.0.1 - - [2020-04-01 23:35:38] "POST /auth/login HTTP/1.1" 500 274 4.761167
[2020-04-01 23:35:39,387] WARNING: Failed to import NanoManager (depends on xbox-smartglass-nano). /nano endpoint will not work!
127.0.0.1 - - [2020-04-01 23:35:39] "GET /device?addr=192.168.178.95 HTTP/1.1" 200 514 2.614691
[2020-04-01 23:35:40,466] ERROR: Exception in CoreProtocol datagram handler
Traceback (most recent call last):
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.6/site-packages/xbox/sg/protocol.py", line 240, in handle
    self._on_message(msg, channel)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.6/site-packages/xbox/sg/protocol.py", line 313, in _on_message
    self._on_json(msg, channel)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.6/site-packages/xbox/sg/protocol.py", line 357, in _on_json
    self.on_json(text, channel)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.6/site-packages/xbox/sg/utils/events.py", line 34, in __call__
    handler(*args, **kwargs)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.6/site-packages/xbox/sg/manager.py", line 71, in _pre_on_json
    self._on_json(data, channel)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.6/site-packages/xbox/stump/manager.py", line 124, in _on_json
    self.console.protocol._set_result(msg.msgid, msg)
  File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.6/site-packages/xbox/sg/protocol.py", line 272, in _set_result
    self._pending[identifier].set(result)
KeyError: '2dce51fd.2'
127.0.0.1 - - [2020-04-01 23:35:42] "GET /auth HTTP/1.1" 200 5668 0.011081
[2020-04-01 23:35:43,484] ERROR: {'success': False, 'message': "Message '2dce51fd.2': 'Message.CONFIGURATION' got no response!"}
127.0.0.1 - - [2020-04-01 23:35:43] "GET /device/FD003F65D1219026/connect HTTP/1.1" 500 220 4.088705
```

**Comment by tuxuser** [comment]
Thanks for reporting.
~Looks related to the acknowledging of stump json messages.~

Gotta look into it.

UPDATE:
This should fix it: https://github.com/OpenXbox/xbox-smartglass-core-python/commit/5850e77471b3f182c75aee2fdbca1dd932d54688#

@foxriver76 Can you confirm?

**Comment by foxriver76** [comment]
works. thanks for the fast fix ;-)

**Comment by foxriver76** [comment]
Thanks for merging into master @tuxuser, could you also publish to pypi? thanks
