### ISSUE TITLE
I have an issue when i executed xbox-rest-server  

### ISSUE THREAD

**Issue by BenjaminAlonsoM** [OpenXbox/xbox-smartglass-core-python#46]
xbox-rest-server                
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:228: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/xbox-rest-server", line 5, in <module>
    from xbox.scripts.rest_server import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xbox/scripts/rest_server.py", line 4, in <module>
    monkey.patch_all()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gevent/monkey.py", line 1137, in patch_all
    patch_ssl(_warnings=_warnings, _first_time=first_time)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gevent/monkey.py", line 183, in ignores
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gevent/monkey.py", line 888, in patch_ssl
    gevent_mod, _ = _patch_module('ssl', _warnings=_warnings)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gevent/monkey.py", line 362, in _patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gevent/ssl.py", line 32, in <module>
    from gevent import _ssl3 as _source # pragma: no cover
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gevent/_ssl3.py", line 171, in <module>
    class SSLSocket(socket):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/gevent/_ssl3.py", line 184, in SSLSocket
    family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None,
NameError: name 'AF_INET' is not defined

**Comment by foxriver76** [comment]
Same as #42. I also have users complaining about this issue.

**Comment by tuxuser** [comment]
Tracked in #42
