### ISSUE TITLE
ModuleNotFoundError: No module named 'xbox.webapi.scripts.tui'

### ISSUE THREAD

**Issue by FlorianLaunay** [OpenXbox/xbox-smartglass-core-python#48]
Hi,

On a brand new Python 3.8 virtual environment (Ubuntu 20.04), every command return the same error :

```
(openxbox) [flaunay@LPT-FLAUNAY ~]$ xbox-tui
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
Traceback (most recent call last):
  File "/home/flaunay/personal/virtualenv/openxbox/bin/xbox-tui", line 5, in <module>
    from xbox.scripts.main_cli import main_tui
  File "/home/flaunay/personal/virtualenv/openxbox/lib/python3.8/site-packages/xbox/scripts/main_cli.py", line 20, in <module>
    from xbox.handlers import tui, gamepad_input, text_input, fallout4_relay
  File "/home/flaunay/personal/virtualenv/openxbox/lib/python3.8/site-packages/xbox/handlers/tui.py", line 17, in <module>
    from xbox.webapi.scripts.tui import WebAPIDisplay
ModuleNotFoundError: No module named 'xbox.webapi.scripts.tui'
```

And visibly, there is no file named `tui.py` in `xbox/webapi/scripts` directory : 

```
(openxbox) [flaunay@LPT-FLAUNAY ~]$ ls -lnh /home/flaunay/personal/virtualenv/openxbox/lib/python3.8/site-packages/xbox/webapi/scripts/
total 24K
-rw-r--r-- 1 212193 200513 3,0K oct.  28 21:13 authenticate.py
-rw-r--r-- 1 212193 200513 3,3K oct.  28 21:13 change_gamertag.py
-rw-r--r-- 1 212193 200513 2,1K oct.  28 21:13 friends.py
-rw-r--r-- 1 212193 200513  389 oct.  28 21:13 __init__.py
drwxr-xr-x 2 212193 200513 4,0K oct.  28 21:13 __pycache__
-rw-r--r-- 1 212193 200513 1,1K oct.  28 21:13 search.py
```

I am missing something ?

Thank you in advance.

*PS : `urwid` is installed*

**Comment by tuxuser** [comment]
Tracked in #42.
